  #开发环境配置
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #启动SpringBoot时，有可能会出现应用mysql服务器的时差问题，
    #在连接中添加'服务器时区'：serverTimezone=GMT/UTC/(需要+8)或serverTimezone=Asia/Shanghai即可解决
    #GMT(格林威治标准时间): 老的时间计量标准
    #UTC(协调 世界时): 现在用的时间计量标准
    #https://baike.sogou.com/v231292.htm?fromTitle=GMT
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password:

  #Jpa配置
  jpa:
    hibernate:
      ddl-auto: update  #可以更改数据库的表结构
    show-sql: true

#日志配置
logging:
  level:  #日志级别
    root: info
    com.xpp: debug
  file: log/blog-dev.log  #日志文件大小默认为10M，按照大小去切分，若文件超出10M，自动切分

#默认采用8080端口号
